### ISSUE TITLE
Missing TextVQA Data in Hugging Face Repository

### ISSUE THREAD

**Issue by rockzz02** [OpenKG-ORG/EasyDetect#3]
The TextVQA data folder is missing in the Hugging Face counterpart repository, which is preventing me from using the dataset provided there.

**Comment by njcx-ai** [comment]
Hello, thank you very much for your interest in our work. The TextVQA data folder you noticed is part of the training set. Please note that we have not uploaded the images associated with this folder for the training set. For the original data, you may refer to the TextVQA dataset. Additionally, we would like to inform you that our project has been migrated to https://github.com/zjunlp/EasyDetect for future maintenance. Please feel free to follow the updates there.
